### ISSUE TITLE
Additional languages

### ISSUE THREAD

**Issue by cashida** [brake4bots/WinSetView#4]
Are there any plans to include additional languages? I could help with German.

**Comment by brake4bots** [comment]
Maybe. I would have to modify the HTA with placeholders for all the text and then dynamically replace the placeholders with text from a language file. Initial testing works, but messes up some of the spacing between sections. If I get it working, I'll come back to you for a German file.

**Comment by brake4bots** [comment]
I'm working on it...

**Comment by brake4bots** [comment]
I have a new version ready with language support along with a preliminary German language.txt file. Please email me directly so I can send those files to you for testing.

**Comment by brake4bots** [comment]
> Are there any plans to include additional languages? I could help with German.

I have a new version ready with language support along with a preliminary German language.txt file. Please email me directly so I can send those files to you for testing.

**Comment by cashida** [comment]
why mail? Why not create an additional branch so that I can commit the changes?

**Comment by brake4bots** [comment]
I have decades of experience creating scripts, but this is my first experience using GitHub, but sure, I can do that...

**Comment by brake4bots** [comment]
> why mail? Why not create an additional branch so that I can commit the changes?

I have decades of experience creating scripts, but this is my first experience using GitHub, but sure, I can do that... Okay, there's now a beta branch with the new version that has language support. There's a German.txt file there for you to edit. Do I need to do anything to grant access?

**Comment by LesFerch** [comment]
@biorpg I see you made a fork of my little project. I'm just curious to know why. Thanks.

**Comment by biorpg** [comment]
I frequently modify the registry classes to customize things top my liking. I've mostly focused on the filetype keys and "Image File Execution Options" in order to customize the context menus and default programs. I have frequently made note of the folder view options that I've noticed while exploring related keys and values, and planned on one day taking the time to configure those- *especially* in the case of the search results view. I forget precisely how I came upon your project.. If I had to guess i would say a syntactical search brought me there. Your project seemed like a good place to start, should I ever find the time to mess with all those settings.

I don't know if it's of any help to you, but these are the (non-standard)properties I frequently find useful to have columns for:

File Description: This property often offers a *much* clearer idea of what a particular application is or does. It is typically for *.exe, *.dll, *.ocx, *.cpl, *.sys files, as the .res resource file that they are compiled with contains it in the standard templates. It is rare to see any Microsoft executables or modules that do not have a File Description.

File Version: Self-explanatory, very similar to Product Version, except that File Version is numeric, and is more consistently present among third-party software.

Subject: This is probably much lesser known, but this field contains a description similar to File Description, but only for Window's installer or Windows Update packages. (*.msi, *.msu, *.cab, etc)

Probably irrelevant, but there is an extended property of executable files called "Original Filename". I've only been able to access it using PE inspection tools, or using a native system .NET API (I forget which.). If it could somehow be incorporated into an explorer column, that would be cool.

________________________________

**Comment by LesFerch** [comment]
Cool. I already have File Version and I can easily add File Description and
Subject. I'll do that and let you know when it's available. Original
Filename does not appear to be an option. Although the data can be
extracted, I don't think there is any way to make Explorer display it in
Details view. Here's some info about extracting the "original filename"
property:
https://stackoverflow.com/questions/45959410/how-can-i-get-a-windows-execuables-original-filename-details-field-using-cmd

I'm working on a new version of WinSetView that will allow selecting any of
the 300+ properties and set sort order, column widths, and group by. There
will be at least a dozen different folder types that can be set
individually or en masse. It's quite an undertaking, especially making it
work in any language. Right now, I'm trying to get a list of folder
properties along with the current language display name. Here's a post with
more details:

https://www.tenforums.com/performance-maintenance/179170-how-list-folder-properties-using-powershell.html#post2219945

Please let me know if you have any idea how to accomplish that. Thanks!

**Comment by biorpg** [comment]
The whole thing seems like one of those areas that MS spent much more time creating and keeping it up to date and available for developers to use than it was ultimately worth, given the general neglect it has had from those developers over the years. I'd say the only significant use that developers have made for them, has been by projects that offer full *replacements* for the file explorer or alternative shells.

When done well, extensions to Explorer are quite nice, and mesh well with the whole system, but there really aren't many examples I can think of outside of commercial software adding a backup/scan/cloud drive to the ribbon. Context menu options are probably the most prominent ways to mod Explorer, but those are best left to the user to customize to their liking, lest they be searching among the overzealous number of options many context menu projects try to present as a bundle.

HardLinkShellExt is actually a fine example of both a masterful use of dynamic context menu entries that bring a frequently useful functionality from the command line closer to where it really belongs, and it also uses some of those rarely touched native mechanisms to add a property page to show which files are hardlinked, and dynamically changes the explorer file/folder icon overlays to indicate files that are hardlinked, symlinked, or are junctions.

Since you are working with how the extended properties are displayed already, I would suggest also taking a look at the other parts of Explorer that pull from the same source of properties. Aside from the columns that are used specifically during a search in Explorer, there is also the subset of properties that can be shown on the status bar, the preview panel, and most of all the tooltip. The tooltips are contextual, based on what is under the cursor, such as the number of files contained in a folder that MS put in the tooltips for folders, I assume for performance as having every folder calculate the number of contained files or size for that matter would be a big performance hit every time the user navigates a folder. The status bar and preview panel I think display properties based on selected files(s), but I personally don't find them useful very often.

**Comment by LesFerch** [comment]
WinSetView v2 currently includes 31 languages. Please help by cleaning up any incorrectly translated text. See the Readme file for more details.
